service: serverless-skeleton

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'staging'}
  region: ${env:AWS_REGION}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - http:
         path: /
         method: get

  world:
    handler: bin/world
    events:
      # - schedule: rate(30 minutes)
